/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activity': RouteRecordInfo<'/activity', '/activity', Record<never, never>, Record<never, never>>,
    '/explore': RouteRecordInfo<'/explore', '/explore', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>>,
    '/user/manage': RouteRecordInfo<'/user/manage', '/user/manage', Record<never, never>, Record<never, never>>,
    '/user/user_cart': RouteRecordInfo<'/user/user_cart', '/user/user_cart', Record<never, never>, Record<never, never>>,
    '/user/user_fav': RouteRecordInfo<'/user/user_fav', '/user/user_fav', Record<never, never>, Record<never, never>>,
    '/user/user_info': RouteRecordInfo<'/user/user_info', '/user/user_info', Record<never, never>, Record<never, never>>,
    '/user/user_order': RouteRecordInfo<'/user/user_order', '/user/user_order', Record<never, never>, Record<never, never>>,
    '/vendor': RouteRecordInfo<'/vendor', '/vendor', Record<never, never>, Record<never, never>>,
  }
}
